import type { Sql, TransactionSql } from "postgres";
import { getInternCredentialInternal } from "@/lib/intern-queries";
import {
  generateCertificatePdf,
  generateCertificatePng,
  generateLetterPdf,
} from "@/lib/documents/generate";

type AnySql = Sql<Record<string, never>> | TransactionSql<Record<string, never>>;

/**
 * Force intern numbers into a gapless 1..N sequence (ordered by creation) and
 * sync the counter. Callers that run this alongside inserts/deletes must hold
 * pg_advisory_xact_lock(hashtext('counter:intern')) inside a transaction.
 */
export async function resequenceInternNumbers(tx: AnySql): Promise<void> {
  // Two-phase update to avoid unique-constraint collisions mid-update.
  await tx`update interns set intern_number = 'TMP-' || id`;
  await tx`
    with ordered as (
      select id, row_number() over (order by id) as rn from interns
    )
    update interns
    set intern_number = 'OLX-INT-' || lpad(ordered.rn::text, 4, '0')
    from ordered
    where interns.id = ordered.id
  `;
  await tx`
    insert into number_counters (name, value)
    values ('intern', (select count(*)::int from interns))
    on conflict (name) do update
    set value = (select count(*)::int from interns)
  `;
}

/**
 * Self-heal stale numbering (e.g. data created before the gapless-numbering
 * rule): if any intern's stored number differs from its expected 1..N value,
 * repair the whole sequence. Cheap read when everything is already correct.
 */
export async function ensureSequentialInternNumbers(sql: Sql<Record<string, never>>): Promise<void> {
  const [row] = await sql<{ stale: boolean }[]>`
    select exists (
      select 1 from (
        select intern_number,
               'OLX-INT-' || lpad(row_number() over (order by id)::text, 4, '0') as want
        from interns
      ) t
      where intern_number <> want
    ) as stale
  `;
  if (!row?.stale) return;
  await sql.begin(async (tx) => {
    await tx`select pg_advisory_xact_lock(hashtext('counter:intern'))`;
    await resequenceInternNumbers(tx);
  });
}

/**
 * Force credential numbers into a gapless per-year sequence
 * (OLX-CERT-YYYY-0001…N, ordered by creation) and sync the per-year counters.
 * Returns the ids of non-draft credentials whose number changed — their stored
 * PDFs print the old number and must be regenerated by the caller.
 * Callers must hold pg_advisory_xact_lock(hashtext('counter:credential')).
 */
export async function resequenceCredentialNumbers(
  tx: AnySql
): Promise<number[]> {
  const before = await tx<{ id: number; num: string; status: string }[]>`
    select id, credential_number as num, status from intern_credentials
  `;
  await tx`update intern_credentials set credential_number = 'TMP-' || id`;
  await tx`
    with ordered as (
      select id,
             extract(year from created_at)::int as yr,
             row_number() over (
               partition by extract(year from created_at)::int order by id
             ) as rn
      from intern_credentials
    )
    update intern_credentials
    set credential_number =
      'OLX-CERT-' || ordered.yr || '-' || lpad(ordered.rn::text, 4, '0')
    from ordered
    where intern_credentials.id = ordered.id
  `;
  await tx`delete from number_counters where name like 'cert-%'`;
  await tx`
    insert into number_counters (name, value)
    select 'cert-' || extract(year from created_at)::int, count(*)::int
    from intern_credentials
    group by 1
  `;
  const after = await tx<{ id: number; num: string; status: string }[]>`
    select id, credential_number as num, status from intern_credentials
  `;
  const beforeNum = new Map(before.map((r) => [r.id, r.num]));
  return after
    .filter((r) => r.status !== "DRAFT" && beforeNum.get(r.id) !== r.num)
    .map((r) => r.id);
}

/**
 * Regenerate and store the documents of published/revoked credentials whose
 * number changed — the certificate and letter print the credential code, so
 * stale PDFs would show the old number. Verification links are unaffected
 * (lookup is by token, never by number).
 */
export async function regenerateCredentialDocuments(
  sql: Sql<Record<string, never>>,
  ids: number[]
): Promise<void> {
  for (const id of ids) {
    const cred = await getInternCredentialInternal(id);
    if (!cred) continue;
    const [certificatePdf, letterPdf, certificatePng] = await Promise.all([
      generateCertificatePdf(cred),
      generateLetterPdf(cred),
      generateCertificatePng(cred),
    ]);
    await sql`
      update intern_credentials
      set certificate_pdf = ${certificatePdf},
          letter_pdf = ${letterPdf},
          certificate_preview_png = ${certificatePng},
          updated_at = now()
      where id = ${id}
    `;
  }
}

/** Self-heal stale credential numbering, regenerating affected documents. */
export async function ensureSequentialCredentialNumbers(
  sql: Sql<Record<string, never>>
): Promise<void> {
  const [row] = await sql<{ stale: boolean }[]>`
    select exists (
      select 1 from (
        select credential_number,
               'OLX-CERT-' || yr || '-' || lpad(rn::text, 4, '0') as want
        from (
          select credential_number,
                 extract(year from created_at)::int as yr,
                 row_number() over (
                   partition by extract(year from created_at)::int order by id
                 ) as rn
          from intern_credentials
        ) t
      ) t2
      where credential_number <> want
    ) as stale
  `;
  if (!row?.stale) return;
  let changed: number[] = [];
  await sql.begin(async (tx) => {
    await tx`select pg_advisory_xact_lock(hashtext('counter:credential'))`;
    changed = await resequenceCredentialNumbers(tx);
  });
  await regenerateCredentialDocuments(sql, changed);
}
